# Generated by Django 4.2.1 on 2023-05-23 21:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancionero', '0002_cancion_letra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='titulo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
