# Generated by Django 4.2.1 on 2023-05-23 21:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancionero', '0003_alter_cancion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='letra',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
