# Generated by Django 4.2.1 on 2023-05-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancionero', '0003_cancion_nro_bp_cancion_nro_sp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='nro_bp',
        ),
        migrations.AlterField(
            model_name='cancion',
            name='nro_sp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
