# Generated by Django 4.2.1 on 2023-06-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancionero', '0004_remove_cancion_nro_bp_alter_cancion_nro_sp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='tono',
        ),
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('canciones', models.ManyToManyField(to='cancionero.cancion')),
            ],
        ),
    ]
